import { createFileRoute } from "@tanstack/react-router";

import { PageHero, Prose } from "@/components/site/page";

export const Route = createFileRoute("/legal/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Farmer's AI" },
      {
        name: "description",
        content:
          "The terms governing use of Farmer's AI, including acceptable use, the advisory nature of reports, accounts and liability.",
      },
      { property: "og:title", content: "Terms of Service — Farmer's AI" },
      { property: "og:description", content: "Terms governing use of the Farmer's AI platform." },
    ],
  }),
  component: Page,
});

function Page() {
  return (
    <>
      <PageHero eyebrow="Legal" title="Terms of Service" description="Last updated: 2 June 2026" />
      <Prose>
        <h2>1. Acceptance</h2>
        <p>
          By using Farmer&apos;s AI you agree to these terms. If you use the service on behalf of an
          organisation, you confirm you are authorised to accept them for that organisation.
        </p>

        <h2>2. The service is advisory</h2>
        <p>
          Reports are generated by an AI system from visual evidence and are estimates. They are{" "}
          <strong>decision support, not a laboratory result, prescription or certification</strong>.
          Always confirm significant agronomic decisions — pesticide application, fertiliser rates,
          harvest timing, food safety and market grading — with qualified local advice, product labels
          and applicable regulation.
        </p>

        <h2>3. Accounts</h2>
        <p>
          You are responsible for the security of your account and for all activity under it. Notify
          us promptly of unauthorised use. We may suspend accounts used to abuse the service.
        </p>

        <h2>4. Acceptable use</h2>
        <ul>
          <li>Do not upload content you have no right to submit.</li>
          <li>Do not attempt to disrupt, overload, reverse engineer or scrape the service.</li>
          <li>Do not present our output as an official inspection, laboratory or certification result.</li>
        </ul>

        <h2>5. Your content</h2>
        <p>
          You retain ownership of the photographs you upload. You grant us the limited licence needed
          to process them in order to produce your report and, where you choose to save it, to store
          it for your account.
        </p>

        <h2>6. Availability</h2>
        <p>
          The service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We
          may change, suspend or discontinue features, and analysis capacity may be rate limited.
        </p>

        <h2>7. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Farmer&apos;s AI is not liable for crop loss, yield
          reduction, input cost, spoilage or other indirect or consequential damages arising from
          reliance on reports generated by the service.
        </p>

        <h2>8. Changes</h2>
        <p>
          We may update these terms. Continued use after an update constitutes acceptance of the
          revised terms.
        </p>

        <h2>9. Contact</h2>
        <p>
          <a href="mailto:legal@farmersai.app" className="text-primary hover:underline">
            legal@farmersai.app
          </a>
        </p>
      </Prose>
    </>
  );
}
